### ISSUE TITLE
Image copyright

### ISSUE THREAD

**Issue by RubeVi** [StratusNetwork/web-development-front#2]
f502973239aba3750e34df9184992b599a3e26b9 those images are from my website.
https://fenixcms.com/static/img/bg/bg1.jpg
https://fenixcms.com/static/img/bg/bg2.jpg
https://fenixcms.com/static/img/bg/bg3.jpg
https://fenixcms.com/static/img/bg/bg4.jpg

**Comment by iPolish** [comment]
Yeah and what where's ur copyright?

**Comment by RubeVi** [comment]
https://fenixcms.com/terms

**Comment by RubeVi** [comment]
check the footer

**Comment by iPolish** [comment]
Oh ok when I'll come home I'll delete it but u didn't had that at footer

**Comment by amactus** [comment]
@RubeVi Please explain how you obtained this copyright. You've used OCN Website code, which is licensed under a GNU Affero General Public License. This means that any modified versions of the code used, must also be open source. Please read the [OCN Repo License info](https://github.com/OvercastNetwork/OCN) and the [GNU License](https://www.gnu.org/licenses/agpl-3.0.en.html)

**Comment by RubeVi** [comment]
@amactus if you can read in the index page i'm using PHP and not ruby on rails.

**Comment by iPolish** [comment]
@RubeVi Anyways that its stolen

**Comment by RubeVi** [comment]
Im not taking any Overcast Network code line.

**Comment by iPolish** [comment]
@RubeVi But Fenix isn't made by you its have been copypasted of some resources on the internet

**Comment by RubeVi** [comment]
LMAO

**Comment by amactus** [comment]
@iPolish why are you replying to this? Can't you see I'm handling it?

@RubeVi okay thanks for clarifying. I'll delete this repository. Sorry for the inconvenience

**Comment by RubeVi** [comment]
@amactus I'm not telling you to delete the repositories, i have no problem if you use it, but just add some credits on the README.md at the bottom,

**Comment by amactus** [comment]
@RubeVi thanks for the offer, but we're working on another site already, so don't worry. Sorry once again
